void launch_calculate_nepfeatmb(
            const double * coeff2,
            const double * coeff3,
            const double * r12,
            const int * NL,
            const int * atom_map,
            const double rcut_radial,
            const double rcut_angular,
            double * feats,
            double * sum_fxyz,
            const int batch_size,
            const int natoms,
            const int neigh_num,
            const int n_max_2b,
            const int n_base_2b,
            const int n_max_3b,
            const int n_base_3b,
            const int lmax_3,
            const int lmax_4,
            const int lmax_5,
            const int n_types,
            const int device_id
);

void launch_calculate_nepfeatmb_grad(
            const double * grad_output,
            const double * coeff2, 
            const double * coeff3, 
            const double * r12,
            const int   * NL, 
            const int   * atom_map, 
            double * sum_fxyz,
            double * grad_coeff2, 
            double * grad_d12_radial, 
            double * grad_coeff3, 
            double * grad_d12_3b,
            const int rcut_radial, 
            const int rcut_angular,
            const int batch_size, 
            const int atom_nums, 
            const int neigh_num, 
            const int n_max_2b, 
            const int n_base_2b, 
            const int n_max_3b, 
            const int n_base_3b,
            const int lmax_3,
            const int lmax_4,
            const int lmax_5,
            const int n_types, 
            const int device_id
);
